# Image Encryption / Decryption using RSA & Chaotic Map

In this project, I designed a image encryption / decryption tool in Python.

In [32]:
import numpy as np # Load numpy module
import cv2 # Load openCV module

### Use cv2 module to load image file
cv2.imread() returns a numpy object in BGR sequence.
Use cv2.COLOR_BGR2RGB to convert it into RGB sequence.

In [33]:
image = cv2.imread("img/img_01.jpg", cv2.COLOR_BGR2RGB)

AttributeError: module 'cv2' has no attribute 'COLOR_'

image = [ [first row : [first column RGB], [second column RGB] ... [last column RGB] ], [second row: [first column RGB], [second column RGB] ... [last column RGB] ] ... ]

Select partial regions of the image and manipulate them through chaotic operations

In [ ]:
dimensions = image.shape
# Height, Width, number of channels in image
height = dimensions[0]
width = dimensions[1]
channels = dimensions[2]
print("Dimension: ", height, width, channels)
print(image)

Dimension:  3280 4928 3
[[[165 156 146]
  [166 157 147]
  [169 160 150]
  ...
  [ 92  93 161]
  [ 90  90 160]
  [ 88  88 158]]

 [[163 154 144]
  [165 156 146]
  [167 158 148]
  ...
  [ 90  91 159]
  [ 93  93 163]
  [ 90  90 160]]

 [[164 155 145]
  [165 156 146]
  [167 158 148]
  ...
  [ 90  91 159]
  [ 92  93 161]
  [ 89  90 158]]

 ...

 [[  4   2   2]
  [  4   2   2]
  [  4   2   2]
  ...
  [  4   2   2]
  [  4   2   2]
  [  5   3   3]]

 [[  4   2   2]
  [  4   2   2]
  [  3   1   1]
  ...
  [  5   3   3]
  [  5   3   3]
  [  4   2   2]]

 [[  4   2   2]
  [  4   2   2]
  [  3   1   1]
  ...
  [  4   2   2]
  [  4   2   2]
  [  4   2   2]]]


## Proposed Encrpytion Algorithm

The proposed image encryption algorithm is a two-step process.

In [34]:
image.astype(int)

AttributeError: 'map' object has no attribute 'astype'